import {readFileSync,writeFileSync,copyFileSync,existsSync,constants} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..');
const catalog=JSON.parse(readFileSync(resolve(root,'resources/reels-review/corrections-20261010.json'),'utf8'));
if(catalog.items.some(i=>i.state!=='ready'))throw new Error('Complete as renderizações antes da galeria.');
const path=resolve(root,'public/uploads/previews/leva02-bloco1-v3/index.html');
const backup=resolve(root,'storage/correcao-instagram-20261010/preview-before.html');
if(!existsSync(backup))copyFileSync(path,backup,constants.COPYFILE_EXCL);
const payload=catalog.items.map(({id,title,status,type,caption,video,poster,articleSlug,originEnvironment,spec,sources,note,reuse,avatarReference})=>({id,title,status,type,caption,video,poster,articleSlug,originEnvironment,sources,note,reuse,avatarReference,scenes:spec.scenes.map(({eyebrow,title,body})=>({eyebrow,title,body})),duration:spec.duration}));
const html=`<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Estratégia Nerd — revisão individual dos Reels</title>
<style>body{margin:0;background:#09131f;color:#e8eef6;font:16px/1.55 system-ui}main{max-width:1180px;margin:auto;padding:24px}h1{font-size:clamp(24px,4vw,38px)}a{color:#85e3ef}header{margin-bottom:28px}.notice{background:#223047;border-left:4px solid #ffc86b;padding:16px;border-radius:8px}nav{display:flex;flex-wrap:wrap;gap:12px;margin:20px 0}input,select{background:#152235;border:1px solid #587089;color:white;border-radius:6px;padding:12px;max-width:100%;box-sizing:border-box}input{flex:1;min-width:180px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,350px),1fr));gap:24px}article{background:#122033;border:1px solid #34485e;border-radius:14px;overflow:hidden}article>div{padding:18px}article h2{font-size:20px;margin:6px 0}video{display:block;width:100%;height:auto;max-height:620px;background:black;aspect-ratio:9/16}small{color:#bdd0e2}.tag{color:#ffc86b}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:inherit}details{margin:14px 0}li{margin-bottom:12px}button{background:#254662;color:white;border:1px solid #587089;padding:9px;border-radius:6px}footer{margin:28px 0;color:#bdd0e2}@media(max-width:450px){main{padding:14px}article>div{padding:14px}}</style>
<main><header><p>ESTRATÉGIA NERD · CORREÇÃO INDIVIDUAL</p><h1>37 conteúdos para conferir, cada um pela sua pauta</h1><p class="notice">Prévia para revisão. Publicação no Instagram ainda não aprovada. Os cancelados 191–194 permanecem cancelados. Os registros publicados 196 e 214 são histórico; os players abaixo mostram versões de revisão.</p><p><a href="?avatar=1">Ver os quatro Reels com seu avatar</a> · 196, 229, 232 e 234: 16 cenas refeitas, com os roteiros e áudios preservados.</p><p>Confira o vídeo completo com áudio em volume confortável. A validação técnica não substitui sua avaliação das imagens, ritmo e música.</p><p><a href="post-77.html">Artigo 77</a> · <a href="post-78.html">Artigo 78</a> · <a href="post-79.html">Artigo 79</a> · <a href="post-80.html">Artigo 80</a></p></header><nav><input id="search" type="search" placeholder="Buscar ID ou assunto" aria-label="Buscar ID ou assunto"><select id="type" aria-label="Tipo"><option value="">Todos os tipos</option><option value="avatar">Com seu avatar (4)</option></select></nav><p id="count" role="status"></p><section id="cards" class="grid"></section><footer>Backups e versões anteriores preservados. 12 vídeos editorialmente aproveitáveis foram mantidos; 25 versões foram renderizadas. Legendas revisadas nos 37 itens.</footer></main>
<script>const items=${JSON.stringify(payload).replaceAll('<','\\u003c')};const base=new URL('../../../',location.href);const cards=document.getElementById('cards');const labels={story:'História / relato',comparison:'Comparação',steps:'Orientação prática',product:'Análise de produto',list:'Recomendações',sound:'Explicação sonora',chat:'Humor / conversa',comedy:'Humor / situação'};const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));Object.keys(labels).forEach(k=>{const o=document.createElement('option');o.value=k;o.textContent=labels[k];document.getElementById('type').append(o)});function draw(){const query=document.getElementById('search').value.toLocaleLowerCase('pt-BR'),type=document.getElementById('type').value;const filtered=items.filter(i=>(!type||(type==='avatar'?i.avatarReference:i.type===type))&&(i.id+' '+i.title).toLocaleLowerCase('pt-BR').includes(query)).sort((a,b)=>a.id===196?-1:b.id===196?1:a.id-b.id);cards.innerHTML=filtered.map(i=>'<article id="post-'+i.id+'"><video controls playsinline preload="none" poster="'+esc(new URL(i.poster,base))+'" src="'+esc(new URL(i.video,base))+'"></video><div><small class="tag">#'+i.id+' · '+esc(labels[i.type])+' · '+(i.avatarReference?'seu avatar · versão 3':i.reuse?'vídeo aproveitado':'nova renderização')+'</small><h2>'+esc(i.title)+'</h2><small>Cadastro original: '+esc(i.status)+' · origem '+esc(i.originEnvironment)+'</small><details><summary>Roteiro e cenas</summary><ol>'+i.scenes.map(s=>'<li><strong>'+esc(s.title)+'</strong><br>'+esc(s.body)+'</li>').join('')+'</ol></details><details><summary>Legenda revisada</summary><pre>'+esc(i.caption)+'</pre></details><p><a href="'+esc(new URL(i.video,base))+'" download>Baixar o vídeo de revisão</a></p></div></article>').join('');document.getElementById('count').textContent=filtered.length?filtered.length+(filtered.length===1?' conteúdo encontrado':' conteúdos encontrados'):'Nenhum conteúdo corresponde à busca';cards.querySelectorAll('video').forEach(v=>v.addEventListener('play',()=>cards.querySelectorAll('video').forEach(other=>{if(other!==v)other.pause()})));}document.getElementById('search').addEventListener('input',draw);document.getElementById('type').addEventListener('change',draw);if(new URLSearchParams(location.search).get('avatar')==='1')document.getElementById('type').value='avatar';draw();</script></html>`;
writeFileSync(path,html);console.log('Galeria oficial atualizada: '+path);
